// 테이블 생성
drop table if exists member CASCADE;
create table member (
                        id bigint generated by default as identity,
                        name varchar(255),
                        primary key (id)
);

// 데이터 넣기
insert into member(name) values ('spring');
insert into member(name) values ('spring2');

